# 11주차_numpy_2025195988_김라래

- 이름 / 학번: 2025195988_김라래
- 과제 내용: NumPy 공식 문서 **NumPy: the absolute basics for beginners** 코드를 따라 코딩하고 실행
- 수행 범위: 시작 부분부터 **Reshaping and flattening multidimensional arrays** 까지


## 1. NumPy 불러오기

NumPy를 사용하기 위해 먼저 `numpy` 패키지를 불러온다. 일반적으로 `np`라는 별칭을 사용한다.


In [1]:
import numpy as np

print("NumPy version:", np.__version__)

NumPy version: 2.3.5


## 2. NumPy 배열 기본 개념

NumPy 배열은 여러 값을 하나의 자료구조로 다룰 수 있게 해준다. 먼저 1차원 배열과 2차원 배열을 만들어본다.


In [2]:
a = np.array([1, 2, 3, 4, 5, 6])
print(a)

b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


## 3. 배열 속성 확인

배열의 차원 수, 모양, 전체 원소 개수, 자료형을 확인한다.


In [3]:
a = np.array([[0, 1, 2, 3],
              [4, 5, 6, 7],
              [8, 9, 10, 11]])

print("ndim:", a.ndim)
print("shape:", a.shape)
print("size:", a.size)
print("dtype:", a.dtype)

ndim: 2
shape: (3, 4)
size: 12
dtype: int64


## 4. 기본 배열 만들기

`np.zeros()`, `np.ones()`, `np.empty()`, `np.arange()`, `np.linspace()`를 사용해 배열을 만든다.


In [4]:
print(np.zeros(2))
print(np.ones(2))
print(np.empty(2))  # 실행 환경에 따라 값이 달라질 수 있음

[0. 0.]
[1. 1.]
[1. 1.]


In [5]:
print(np.arange(4))
print(np.arange(2, 9, 2))
print(np.linspace(0, 10, num=5))

[0 1 2 3]
[2 4 6 8]
[ 0.   2.5  5.   7.5 10. ]


In [6]:
x = np.ones(2, dtype=np.int64)
print(x)
print(x.dtype)

[1 1]
int64


## 5. 배열 정렬과 연결

`np.sort()`로 정렬하고, `np.concatenate()`로 배열을 연결한다.


In [7]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
print(np.sort(arr))

[1 2 3 4 5 6 7 8]


In [8]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

print(np.concatenate((a, b)))

[1 2 3 4 5 6 7 8]


In [9]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

print(np.concatenate((x, y), axis=0))

[[1 2]
 [3 4]
 [5 6]]


## 6. 배열의 차원, 크기, 모양 확인

3차원 배열을 만들고 `ndim`, `size`, `shape`를 확인한다.


In [10]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]]])

print("ndim:", array_example.ndim)
print("size:", array_example.size)
print("shape:", array_example.shape)

ndim: 3
size: 24
shape: (3, 2, 4)


## 7. 배열 모양 바꾸기

`reshape()`는 원소 개수는 그대로 두고 배열의 모양을 바꾼다.


In [11]:
a = np.arange(6)
print(a)

b = a.reshape(3, 2)
print(b)

print(np.reshape(a, shape=(1, 6), order='C'))

[0 1 2 3 4 5]
[[0 1]
 [2 3]
 [4 5]]
[[0 1 2 3 4 5]]


## 8. 1차원 배열을 2차원 배열로 바꾸기

`np.newaxis`와 `np.expand_dims()`를 사용하면 배열에 새로운 축을 추가할 수 있다.


In [12]:
a = np.array([1, 2, 3, 4, 5, 6])
print("원래 shape:", a.shape)

row_vector = a[np.newaxis, :]
print("row_vector shape:", row_vector.shape)
print(row_vector)

col_vector = a[:, np.newaxis]
print("col_vector shape:", col_vector.shape)
print(col_vector)

원래 shape: (6,)
row_vector shape: (1, 6)
[[1 2 3 4 5 6]]
col_vector shape: (6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [13]:
a = np.array([1, 2, 3, 4, 5, 6])

b = np.expand_dims(a, axis=1)
print("axis=1:", b.shape)
print(b)

c = np.expand_dims(a, axis=0)
print("axis=0:", c.shape)
print(c)

axis=1: (6, 1)
[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]
axis=0: (1, 6)
[[1 2 3 4 5 6]]


## 9. 인덱싱과 슬라이싱

배열에서 원하는 위치의 값을 가져오거나 조건에 맞는 값만 선택한다.


In [14]:
data = np.array([1, 2, 3])

print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:])

2


[1 2]
[2 3]
[2 3]


In [15]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(a[a < 5])

[1 2 3 4]


In [16]:
five_up = (a >= 5)
print(a[five_up])

divisible_by_2 = a[a % 2 == 0]
print(divisible_by_2)

c = a[(a > 2) & (a < 11)]
print(c)

[ 5  6  7  8  9 10 11 12]
[ 2  4  6  8 10 12]
[ 3  4  5  6  7  8  9 10]


In [17]:
b = np.nonzero(a < 5)
print(b)

list_of_coordinates = list(zip(b[0], b[1]))
for coord in list_of_coordinates:
    print(coord)

print(a[b])

(array([0, 0, 0, 0]), array([0, 1, 2, 3]))
(np.int64(0), np.int64(0))
(np.int64(0), np.int64(1))
(np.int64(0), np.int64(2))
(np.int64(0), np.int64(3))
[1 2 3 4]


In [18]:
not_there = np.nonzero(a == 42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


## 10. 기존 데이터에서 새 배열 만들기

슬라이싱, `np.vstack()`, `np.hstack()`, `np.hsplit()`, `view()`, `copy()`를 사용한다.


In [19]:
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

arr1 = a[3:8]
print(arr1)

[4 5 6 7 8]


In [20]:
a1 = np.array([[1, 1],
               [2, 2]])

a2 = np.array([[3, 3],
               [4, 4]])

print(np.vstack((a1, a2)))
print(np.hstack((a1, a2)))

[[1 1]
 [2 2]
 [3 3]
 [4 4]]
[[1 1 3 3]
 [2 2 4 4]]


In [21]:
x = np.arange(1, 25).reshape(2, 12)
print(x)

print(np.hsplit(x, 3))
print(np.hsplit(x, (3, 4)))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]
 [13 14 15 16 17 18 19 20 21 22 23 24]]
[array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]]), array([[ 5,  6,  7,  8],
       [17, 18, 19, 20]]), array([[ 9, 10, 11, 12],
       [21, 22, 23, 24]])]
[array([[ 1,  2,  3],
       [13, 14, 15]]), array([[ 4],
       [16]]), array([[ 5,  6,  7,  8,  9, 10, 11, 12],
       [17, 18, 19, 20, 21, 22, 23, 24]])]


In [22]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b1 = a[0, :]
print("b1:", b1)

b1[0] = 99
print("a after changing b1:")
print(a)

b1: [1 2 3 4]
a after changing b1:
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [23]:
a = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

b2 = a.copy()
b2[0, 0] = 99

print("원본 a:")
print(a)
print("복사본 b2:")
print(b2)

원본 a:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
복사본 b2:
[[99  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## 11. 기본 배열 연산

배열끼리 더하기, 빼기, 곱하기, 나누기 연산을 수행한다.


In [24]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)

print(data + ones)
print(data - ones)
print(data * data)
print(data / data)

[2 3]
[0 1]
[1 4]
[1. 1.]


In [25]:
a = np.array([1, 2, 3, 4])
print(a.sum())

10


In [26]:
b = np.array([[1, 1], [2, 2]])
print(b.sum(axis=0))  # 열 방향 합계
print(b.sum(axis=1))  # 행 방향 합계

[3 3]
[2 4]


## 12. 브로드캐스팅

배열과 하나의 숫자를 함께 연산할 수 있다.


In [27]:
data = np.array([1.0, 2.0])
print(data * 1.6)

[1.6 3.2]


## 13. 유용한 배열 연산

최댓값, 최솟값, 합계, 평균 등을 계산한다.


In [28]:
data = np.array([1, 2, 3])

print(data.max())
print(data.min())
print(data.sum())
print(data.mean())

3
1
6
2.0


In [29]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

print(a.sum())
print(a.min())
print(a.min(axis=0))

4.8595784
0.05093587
[0.12697628 0.05093587 0.26590556 0.5510652 ]


## 14. 행렬 만들기

2차원 배열을 만들고 행렬 연산 예제를 확인한다.


In [30]:
data = np.array([[1, 2], [3, 4], [5, 6]])
print(data)

print(data[0, 1])
print(data[1:3])
print(data[0:2, 0])

[[1 2]
 [3 4]
 [5 6]]
2
[[3 4]
 [5 6]]
[1 3]


In [31]:
print(data.max())
print(data.min())
print(data.sum())

print(data.max(axis=0))
print(data.max(axis=1))

6
1
21
[5 6]
[2 4 6]


In [32]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])

print(data + ones)

[[2 3]
 [4 5]]


In [33]:
data = np.array([[1, 2], [3, 4], [5, 6]])
ones_row = np.array([[1, 1]])

print(data + ones_row)

[[2 3]
 [4 5]
 [6 7]]


In [34]:
print(np.ones((4, 3, 2)))
print(np.ones(3))
print(np.zeros(3))
print(np.random.default_rng(0).random(3))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]
[1. 1. 1.]
[0. 0. 0.]
[0.63696169 0.26978671 0.04097352]


In [35]:
rng = np.random.default_rng(0)

print(rng.integers(5, size=(2, 4)))
print(rng.random((3, 2)))

[[4 3 2 1]
 [1 0 0 0]]
[[0.81327024 0.91275558]
 [0.60663578 0.72949656]
 [0.54362499 0.93507242]]


## 15. 고유값과 개수 구하기

`np.unique()`를 사용하면 중복을 제거한 고유값을 확인할 수 있다.


In [36]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

unique_values = np.unique(a)
print(unique_values)

unique_values, indices_list = np.unique(a, return_index=True)
print(indices_list)

unique_values, occurrence_count = np.unique(a, return_counts=True)
print(occurrence_count)

[11 12 13 14 15 16 17 18 19 20]
[ 0  2  3  4  5  6  7 12 13 14]
[3 2 2 2 1 1 1 1 1 1]


In [37]:
a_2d = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12],
                 [1, 2, 3, 4]])

unique_values = np.unique(a_2d)
print(unique_values)

unique_rows = np.unique(a_2d, axis=0)
print(unique_rows)

unique_rows, indices, occurrence_count = np.unique(
    a_2d, axis=0, return_counts=True, return_index=True
)

print(indices)
print(occurrence_count)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[0 1 2]
[2 1 1]


## 16. 행렬 전치와 reshape

`reshape()`, `transpose()`, `.T`를 사용해 행렬의 모양과 방향을 바꾼다.


In [38]:
data = np.array([1, 2, 3, 4, 5, 6])

print(data.reshape(2, 3))
print(data.reshape(3, 2))

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


In [39]:
arr = np.arange(6).reshape((2, 3))
print(arr)

print(arr.transpose())
print(arr.T)

[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[[0 3]
 [1 4]
 [2 5]]


## 17. 배열 뒤집기

`np.flip()`을 사용하여 1차원 배열과 2차원 배열을 뒤집는다.


In [40]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

reversed_arr = np.flip(arr)
print("Reversed Array:", reversed_arr)

Reversed Array: [8 7 6 5 4 3 2 1]


In [41]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

reversed_arr = np.flip(arr_2d)
print(reversed_arr)

reversed_arr_rows = np.flip(arr_2d, axis=0)
print(reversed_arr_rows)

reversed_arr_columns = np.flip(arr_2d, axis=1)
print(reversed_arr_columns)

[[12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]
[[ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]
[[ 4  3  2  1]
 [ 8  7  6  5]
 [12 11 10  9]]


In [42]:
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

arr_2d[1] = np.flip(arr_2d[1])
print(arr_2d)

arr_2d[:, 1] = np.flip(arr_2d[:, 1])
print(arr_2d)

[[ 1  2  3  4]
 [ 8  7  6  5]
 [ 9 10 11 12]]
[[ 1 10  3  4]
 [ 8  7  6  5]
 [ 9  2 11 12]]


## 18. 다차원 배열 펼치기

`flatten()`과 `ravel()`은 다차원 배열을 1차원 배열로 펼칠 때 사용한다.  
`flatten()`은 복사본을 만들고, `ravel()`은 원본 배열을 참조하는 view를 만들 수 있다.


In [43]:
x = np.array([[1, 2, 3, 4],
              [5, 6, 7, 8],
              [9, 10, 11, 12]])

print(x.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [44]:
a1 = x.flatten()
a1[0] = 99

print("Original array:")
print(x)
print("New array:")
print(a1)

Original array:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New array:
[99  2  3  4  5  6  7  8  9 10 11 12]


In [45]:
a2 = x.ravel()
a2[0] = 98

print("Original array:")
print(x)
print("New array:")
print(a2)

Original array:
[[98  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
New array:
[98  2  3  4  5  6  7  8  9 10 11 12]
